=== api-evangelist/airflow/json-schema/airflow-task-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/airflow/refs/heads/main/json-schema/airflow-task-response-schema.json",
  "title": "TaskResponse",
  "description": "Task serializer for responses.",
  "type": "object",
  "properties": {
    "task_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Task Id"
    },
    "task_display_name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Task Display Name"
    },
    "owner": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Owner"
    },
    "start_date": {
      "anyOf": [
        {
          "type": "string",
          "format": "date-time"
        },
        {
          "type": "null"
        }
      ],
      "title": "Start Date"
    },
    "end_date": {
      "anyOf": [
        {
          "type": "string",
          "format": "date-time"
        },
        {
          "type": "null"
        }
      ],
      "title": "End Date"
    },
    "trigger_rule": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Trigger Rule"
    },
    "depends_on_past": {
      "type": "boolean",
      "title": "Depends On Past"
    },
    "wait_for_downstream": {
      "type": "boolean",
      "title": "Wait For Downstream"
    },
    "retries": {
      "anyOf": [
        {
          "type": "number"
        },
        {
          "type": "null"
        }
      ],
      "title": "Retries"
    },
    "queue": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Queue"
    },
    "pool": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Pool"
    },
    "pool_slots": {
      "anyOf": [
        {
          "type": "number"
        },
        {
          "type": "null"
        }
      ],
      "title": "Pool Slots"
    },
    "execution_timeout": {
      "anyOf": [
        {
          "$ref": "#/components/schemas/TimeDelta"
        },
        {
          "type": "null"
        }
      ]
    },
    "retry_delay": {
      "anyOf": [
        {
          "$ref": "#/components/schemas/TimeDelta"
        },
        {
          "type": "null"
        }
      ]
    },
    "retry_exponential_backoff": {
      "type": "number",
      "title": "Retry Exponential Backoff"
    },
    "priority_weight": {
      "anyOf": [
        {
          "type": "number"
        },
        {
          "type": "null"
        }
      ],
      "title": "Priority Weight"
    },
    "weight_rule": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Weight Rule"
    },
    "ui_color": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Ui Color"
    },
    "ui_fgcolor": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Ui Fgcolor"
    },
    "template_fields": {
      "anyOf": [
        {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "title": "Template Fields"
    },
    "downstream_task_ids": {
      "anyOf": [
        {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "title": "Downstream Task Ids"
    },
    "doc_md": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Doc Md"
    },
    "operator_name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Operator Name"
    },
    "params": {
      "anyOf": [
        {
          "additionalProperties": true,
          "type": "object"
        },
        {
          "type": "null"
        }
      ],
      "title": "Params"
    },
    "class_ref": {
      "anyOf": [
        {
          "additionalProperties": true,
          "type": "object"
        },
        {
          "type": "null"
        }
      ],
      "title": "Class Ref"
    },
    "is_mapped": {
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "type": "null"
        }
      ],
      "title": "Is Mapped"
    },
    "extra_links": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "title": "Extra Links",
      "description": "Extract and return extra_links.",
      "readOnly": true
    }
  },
  "required": [
    "task_id",
    "task_display_name",
    "owner",
    "start_date",
    "end_date",
    "trigger_rule",
    "depends_on_past",
    "wait_for_downstream",
    "retries",
    "queue",
    "pool",
    "pool_slots",
    "execution_timeout",
    "retry_delay",
    "retry_exponential_backoff",
    "priority_weight",
    "weight_rule",
    "ui_color",
    "ui_fgcolor",
    "template_fields",
    "downstream_task_ids",
    "doc_md",
    "operator_name",
    "params",
    "class_ref",
    "is_mapped",
    "extra_links"
  ]
}

=== api-evangelist/airflow/examples/airflow-task-response-example.json
{
  "task_id": "abc123",
  "task_display_name": "example-name",
  "owner": "example-value",
  "start_date": "example-value",
  "end_date": "example-value",
  "trigger_rule": "example-value",
  "depends_on_past": true,
  "wait_for_downstream": true,
  "retries": "example-value",
  "queue": "example-value",
  "pool": "example-value",
  "pool_slots": "example-value",
  "execution_timeout": "example-value",
  "retry_delay": "example-value",
  "retry_exponential_backoff": 1,
  "priority_weight": "example-value",
  "weight_rule": "example-value",
  "ui_color": "example-value",
  "ui_fgcolor": "example-value",
  "template_fields": "example-value",
  "downstream_task_ids": "abc123",
  "doc_md": "example-value",
  "operator_name": "example-name",
  "params": "example-value",
  "class_ref": "example-value",
  "is_mapped": "example-value",
  "extra_links": []
}
